component: website

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-north-1

service:
  name: studio-booking

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

inputs:
  src: ./build
  hook: npm run build